Stop specifying the full python version for black (#117)
python3.6 causes weird venv issues for at least josh11b -- not sure why. 

```
$ ls -l /usr/bin/python3.6
-rwxr-xr-x 2 root root 4538776 Jan  2  2019 /usr/bin/python3.6*
$ virtualenv -p python3.6 venv
RuntimeError: failed to find interpreter for Builtin discover of python_spec='python3.6'
```