Use a switch in StringifyTypeExpr
Get a compiler error when a case isn't handled instead of a runtime
CHECK failure.

Error confirmed locally, it looks like:
```
toolchain/sem_ir/stringify_type.cpp:120:13: error: enumeration value 'Name' not handled in switch [-Werror,-Wswitch]
  120 |     switch (step.kind) {
      |             ^~~~~~~~~
1 error generated.
```