Produce good looking diagnostics on ambiguous built-in operators. Now we produce things like: bug1.cpp:21:11: error: use of overloaded operator '->*' is ambiguous         int i = c->*pmf;        // expected-error {{use of overloaded operator '->*' is ambiguous}} \                 ~^  ~~~ bug1.cpp:21:11: note: built-in candidate operator ->* ('struct A volatile *', 'int const struct A::*') bug1.cpp:21:11: note: built-in candidate operator ->* ('struct A volatile *', 'int restrict struct A::*') ...
Still need to look at an issue (indicated as FIXME in the test case).

llvm-svn: 83650